name: Update Release Branch on Version Change

on:
  push:
    branches:
      - main
    paths:
      - 'backend/consts/version.go'

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: setup ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: setup bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: setup go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.23.2'
        cache-dependency-path: backend/go.sum
    - name: merge main into release
      run: |
        git remote set-url origin git@github.com:janie314/gnuplex.git
        git config user.name "deploy.yml workflow"
        git config user.email "x@example.com"
        git checkout release 
        git merge main -X theirs --allow-unrelated-histories
    - name: build gnuplex
      run: |
        bundle install
        bundle exec rake build
    - name: update release branch
      run: |
        umask 077
        echo "${{ secrets.GNUPLEX_DEPLOY }}" >>/tmp/gnuplex-deploy
        version_output=$(./backend/bin/gnuplex -version)
        git add .
        git commit -m "$version_output"
        GIT_SSH_COMMAND="ssh -i /tmp/gnuplex-deploy" git push origin release