on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    name: testing and linting this branch
    steps:
    - name: check out this repo
      uses: actions/checkout@v5
      with:
        lfs: true
    - name: setup bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: lint frontend code
      run: |
        bun i
        bun run biome ci --verbose
    - name: check for TODO string instances
      run: |
        git ls-files | grep -v test-branch\.yml | xargs grep -Ii todo | wc -l | xargs ruby -e 'exit ARGV[0].to_i == 0'
